# Generated by Django 5.0.6 on 2026-09-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(default='Cash', max_length=50)),
                ('date', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='Miscellaneous', max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(default='Ganesh Chaturthi', max_length=200)),
                ('street_name', models.CharField(default='Your Street / Colony Name', max_length=200)),
                ('date_range', models.CharField(default='Set festival dates', max_length=200)),
                ('upi_name', models.CharField(blank=True, default='', max_length=200)),
                ('upi_id', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(default='ganpati123', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
